# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-sample

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: ${opt:stage, 'dev'}
  region: ${file(./conf/config.${self:provider.stage}.json):REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}_settings"
  environment:
    REGION: ${file(./conf/config.${self:provider.stage}.json):REGION}
    USER_POOL_ID: ${file(./conf/config.${self:provider.stage}.json):USER_POOL_ID}
    CLIENT_ID: ${file(./conf/config.${self:provider.stage}.json):CLIENT_ID}
    ONLY_API_GATEWAY: ${file(./conf/config.${self:provider.stage}.json):ONLY_API_GATEWAY}
    STAGE: ${self:provider.stage}

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: ./config/migrations

functions:
  app:
    handler: index.handler
    events:
      - http: 'GET /'
      - http: 'GET /top'
      - http: 'GET /sign-up'
      - http: 'GET /confirm/{proxy+}'
  getSettings:
    handler: api.get
    events:
      - http:
          path: api/settings
          method: get
          authorizer:
            arn: ${file(./conf/config.${self:provider.stage}.json):USER_POOL_ARN}
  postSettings:
    handler: api.post
    events:
      - http:
          path: api/settings
          method: post
          authorizer:
            arn: ${file(./conf/config.${self:provider.stage}.json):USER_POOL_ARN}
plugins:
  - serverless-dynamodb-local
  - serverless-offline

resources:
  Resources:
    SettingsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${self:provider.stage}_settings"
